(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const app=firebase.apps.length?firebase.app():firebase.initializeApp(window.MOHAJER_FIREBASE_CONFIG),auth=app.auth(),db=app.firestore();
const iframe=$('#preview'),canvas=$('#canvas'),toast=$('#toast');
let drafts={},selected=null,selectedKey='',device='desktop',undo=[],redo=[],pagePath='/products/steel-billet/';
const clone=v=>JSON.parse(JSON.stringify(v));
const notify=m=>{toast.textContent=m;toast.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove('show'),2400)};
const esc=v=>CSS.escape(String(v));
const text=(el,v)=>{el.replaceChildren();String(v??'').split(/<br\s*\/?>/i).forEach((x,i)=>{if(i)el.append(el.ownerDocument.createElement('br'));el.append(el.ownerDocument.createTextNode(x))})};
const hex=v=>{const m=String(v||'').match(/\d+/g);return m?`#${m.slice(0,3).map(x=>(+x).toString(16).padStart(2,'0')).join('')}`:'#000000'};
function selector(el){if(el.dataset.key)return `[data-key="${esc(el.dataset.key)}"]`;if(el.id)return `#${esc(el.id)}`;let a=[],n=el;while(n&&n!==n.ownerDocument.body&&a.length<8){let p=n.tagName.toLowerCase(),c=[...n.classList].find(x=>!x.startsWith('admin-'));if(c)p+='.'+esc(c);let sib=[...n.parentElement.children].filter(x=>x.tagName===n.tagName);if(sib.length>1)p+=`:nth-of-type(${sib.indexOf(n)+1})`;a.unshift(p);n=n.parentElement}return a.join(' > ')}
function apply(d,doc){if(!d?.selector)return;let el;try{el=doc.querySelector(d.selector)}catch{return}if(!el)return;if(d.type==='image'&&d.content)el.src=d.content;if(d.type==='text')text(el,d.content);Object.entries(d.styles||{}).forEach(([k,v])=>{if(v!==''&&v!=null)el.style[k]=v});Object.entries(d.responsive?.[device]||{}).forEach(([k,v])=>{if(v)el.style[k]=v});if(d.hover?.scale&&d.hover.scale!=='1'){el.dataset.editorHover=d.hover.scale}}
function applyAll(){const doc=iframe.contentDocument;if(!doc)return;Object.values(drafts).forEach(d=>apply(d,doc))}
function prepare(){const doc=iframe.contentDocument;if(!doc)return;doc.getElementById('mohajer-editor-overlay')?.remove();const s=doc.createElement('style');s.id='mohajer-editor-overlay';s.textContent=`[data-key],img,section,article,button,a,.product-card,.feature-item-new,.dept-card,.ss-product-card{cursor:pointer!important}[data-key]:hover,img:hover,section:hover,article:hover,button:hover,a:hover,.product-card:hover,.feature-item-new:hover,.dept-card:hover,.ss-product-card:hover{outline:2px solid #3478f6!important;outline-offset:2px!important}.mohajer-selected{outline:3px solid #f2b941!important;outline-offset:3px!important}[data-editor-hover]{transition:transform .2s}[data-editor-hover]:hover{transform:scale(var(--editor-hover-scale,1.02))!important}`;doc.head.append(s);applyAll();doc.addEventListener('click',e=>{const el=e.target.closest('[data-key],img,.product-card,.feature-item-new,.dept-card,.ss-product-card,section,article,button,a');if(!el)return;e.preventDefault();e.stopPropagation();select(el)},true)}
function set(id,v){const x=$('#'+id);if(x)x.value=v??''}
function select(el){selected?.classList.remove('mohajer-selected');selected=el;selected.classList.add('mohajer-selected');selectedKey=selector(el);const type=el.tagName==='IMG'?'image':el.dataset.key?'text':'container';el.dataset.editorType=type;$('#selectedTitle').textContent=el.dataset.key||el.tagName.toLowerCase();$('#selectedKey').value=selectedKey;$('#emptyInspector').classList.add('hidden');$('#inspector').classList.remove('hidden');const c=getComputedStyle(el);set('fontSize',c.fontSize);set('fontWeight',c.fontWeight);set('lineHeight',c.lineHeight);set('letterSpacing',c.letterSpacing);set('textAlign',c.textAlign);set('textTransform',c.textTransform);set('textColor',hex(c.color));set('textColorText',hex(c.color));set('bgColor',hex(c.backgroundColor));set('bgColorText',hex(c.backgroundColor));set('opacity',c.opacity);set('margin',c.margin);set('padding',c.padding);set('gap',c.gap);set('width',c.width);set('height',c.height);set('minWidth',c.minWidth);set('maxWidth',c.maxWidth);set('position',c.position);set('zIndex',c.zIndex);set('radius',c.borderRadius);set('border',c.border);set('shadow',c.boxShadow);set('bgImage',c.backgroundImage==='none'?'':c.backgroundImage.replace(/^url\(["']?|["']?\)$/g,''));set('animation',c.animationName==='none'?'':c.animationName);set('animationDuration',c.animationDuration);set('animationDelay',c.animationDelay);set('hoverScale',drafts[selectedKey]?.hover?.scale||'1');$('#textValue').value=type==='text'?(el.innerText||el.textContent||'').trim():'';$('#linkValue').value=el.closest('a')?.href||'';$('#newTab').checked=el.closest('a')?.target==='_blank';el.scrollIntoView({block:'center',behavior:'smooth'})}
const fields=['fontSize','fontWeight','lineHeight','letterSpacing','textAlign','textTransform','opacity','margin','padding','gap','width','height','minWidth','maxWidth','position','zIndex','border','shadow'];
function styles(){const o={};fields.forEach(id=>{const x=$('#'+id);if(x?.value)o[id]=x.value});o.borderRadius=$('#radius').value||'';o.color=$('#textColor').value||'';o.backgroundColor=$('#bgColor').value||'';if($('#bgImage').value){o.backgroundImage=`url("${$('#bgImage').value}")`;o.backgroundSize='cover';o.backgroundPosition='center'}o.animationName=$('#animation').value||'';o.animationDuration=$('#animationDuration').value||'';o.animationDelay=$('#animationDelay').value||'';return o}
function snapshot(){return clone(drafts)}
function capture(){if(!selected)return notify('ابتدا یک عنصر را انتخاب کنید');undo.push(snapshot());if(undo.length>50)undo.shift();redo=[];const old=drafts[selectedKey]||{},type=selected.dataset.editorType||'container';drafts[selectedKey]={...old,selector:selectedKey,type,content:type==='image'?(selected.src||''):$('#textValue').value.replace(/\n/g,'<br>'),styles:{...(old.styles||{}),...styles()},responsive:{...(old.responsive||{}),[device]:{fontSize:$('#responsiveFont').value,width:$('#responsiveWidth').value,margin:$('#responsiveMargin').value,padding:$('#responsivePadding').value}},hover:{scale:$('#hoverScale').value||'1'},schemaVersion:5};applyAll();saveLocal();historyButtons();$('#saveState').textContent='● Draft آماده است';notify('تغییر در Draft اعمال شد')}
function saveLocal(){try{localStorage.setItem('mohajer-editor-pro-draft',JSON.stringify(drafts))}catch{}}
function historyButtons(){$('#undoBtn').disabled=!undo.length;$('#redoBtn').disabled=!redo.length}
async function remote(){if(!auth.currentUser)throw Error('not authenticated');await db.collection('siteContent').doc('draft').set({content:drafts,updatedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedBy:auth.currentUser.uid,schemaVersion:5})}
async function publish(){const live=await db.collection('siteContent').doc('published').get();const id=`v-${Date.now()}`;await db.collection('siteVersions').doc(id).set({content:live.exists?live.data().content:{},createdAt:firebase.firestore.FieldValue.serverTimestamp(),createdBy:auth.currentUser.uid,source:'pre-publish',page:pagePath});await db.collection('siteContent').doc('published').set({content:drafts,updatedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedBy:auth.currentUser.uid,versionId:id,schemaVersion:5})}
function pages(){const b=$('#leftContent');b.innerHTML='';[['صفحه اصلی','/'],['Steel Billet','/products/steel-billet/'],['Steel Beam','/products/steel-beam/'],['Steel Pipe','/products/steel-pipe/'],['Rebar','/products/rebar/'],['Steel Plate','/products/steel-plate/'],['Steel Angle','/products/steel-angle/'],['Steel Channel','/products/steel-channel/'],['Steel Slab','/products/steel-slab/']].forEach(([n,p])=>{const x=document.createElement('button');x.className='page-item';x.innerHTML=`${n}<small>${p}</small>`;x.onclick=()=>{pagePath=p;$('#pageTitle').textContent=n;$('#pagePath').textContent=p;if(p!=='/products/steel-billet/')return notify('این نسخه ابتدا برای Steel Billet فعال است');iframe.src='../../products/steel-billet/'};b.append(x)})}
function elements(){const b=$('#leftContent');b.innerHTML='';['Section','Container','Heading','Paragraph','Text','Image','Button','Link','Icon','Card','Badge','Statistic','Table','List','Video','Gallery','FAQ','Divider','Logo','Navigation','Footer'].forEach(t=>{const x=document.createElement('button');x.className='page-item';x.textContent='＋ '+t;x.onclick=()=>addElement(t);b.append(x)})}
function addElement(type){if(!selected)return notify('ابتدا یک Container یا Section را انتخاب کنید');undo.push(snapshot());const doc=iframe.contentDocument,el=doc.createElement(type==='Heading'?'h2':type==='Paragraph'?'p':type==='Button'?'button':type==='Image'?'img':'div');el.textContent=['Heading','Paragraph','Text','Button'].includes(type)?type:'New '+type;el.dataset.editorNew='1';el.style.cssText='padding:12px;margin:8px;border:1px dashed #999';if(type==='Image')el.src='https://placehold.co/600x300?text=Image';selected.append(el);const key=`[data-editor-new="${Date.now()}"]`;el.dataset.editorNew=key.slice(1,-1);drafts[key]={selector, type:type==='Image'?'image':'text',content:type==='Image'?el.src:el.textContent,styles:{padding:'12px',margin:'8px',border:'1px dashed #999'},schemaVersion:5};selected.classList.remove('mohajer-selected');select(el);saveLocal();notify(type+' به Draft اضافه شد')}
function media(){const b=$('#leftContent');b.innerHTML='<div class="page-item"><b>Media Library</b><p class="hint">برای امنیت، آپلود دائمی فایل‌ها نیازمند Firebase Storage است. URL تصویر را در عنصر Image وارد کنید.</p></div>';}
async function historyView(){const b=$('#leftContent');b.innerHTML='<div class="page-item">در حال بارگذاری تاریخچه…</div>';try{const s=await db.collection('siteVersions').orderBy('createdAt','desc').limit(20).get();b.innerHTML='';s.forEach(d=>{const x=document.createElement('button');x.className='page-item';const v=d.data();x.textContent=v.versionId||d.id;x.onclick=async()=>{if(!confirm('این نسخه فقط به Draft برگردد؟'))return;drafts=clone(v.content||{});saveLocal();applyAll();notify('Rollback به Draft انجام شد')};b.append(x)});if(!s.size)b.innerHTML='<div class="page-item">تاریخچه‌ای وجود ندارد.</div>'}catch{b.innerHTML='<div class="page-item">تاریخچه قابل دریافت نیست.</div>'}}
function seo(){const b=$('#leftContent');b.innerHTML='<div class="page-item"><b>SEO Manager</b><p class="hint">Title · Description · Canonical · Robots · Open Graph در Draft ذخیره می‌شوند. انتشار فقط با Publish انجام می‌شود.</p></div>';}
function ai(){const b=$('#leftContent');b.innerHTML='<div class="page-item"><b>AI Design Assistant</b><p class="hint">AI فقط روی عنصر انتخاب‌شده مجاز است. Context شامل صفحه، selector، نوع، محتوا، style و responsive است. اتصال Provider باید از Backend امن انجام شود و کلید در Frontend ذخیره نمی‌شود.</p></div>';if(selected){const x=document.createElement('button');x.className='page-item primary';x.textContent='ساخت Context برای AI';x.onclick=()=>navigator.clipboard?.writeText(JSON.stringify({page:pagePath,selector:selectedKey,type:selected.dataset.editorType,content:$('#textValue').value,styles:drafts[selectedKey]?.styles||{},responsive:drafts[selectedKey]?.responsive||{}},null,2));b.append(x)}}
function navView(v){$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='pages')pages();else if(v==='elements')elements();else if(v==='media')media();else if(v==='history')historyView();else if(v==='seo')seo();else if(v==='ai')ai();else $('#leftContent').innerHTML='<div class="page-item"><b>Settings</b><p class="hint">Preview isolation, Draft persistence و Publish Guard فعال هستند.</p></div>'}
async function boot(){try{drafts=JSON.parse(localStorage.getItem('mohajer-editor-pro-draft')||'{}')}catch{drafts={}}pages();try{const s=await db.collection('siteContent').doc('draft').get();if(s.exists)drafts={...s.data().content,...drafts}}catch(e){console.warn(e)}saveLocal();historyButtons()}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button');b.disabled=true;try{await auth.setPersistence(firebase.auth.Auth.Persistence.SESSION);await auth.signInWithEmailAndPassword('amirgzva@gmail.com',$('#adminPassword').value)}catch{$('#loginError').textContent='ورود ناموفق بود؛ رمز پنل قبلی را بررسی کنید'}finally{b.disabled=false}});
auth.onAuthStateChanged(u=>{const ok=!!u;$('#loginGate').classList.toggle('hidden',ok);$('#app').classList.toggle('locked',!ok);if(ok)boot()});
iframe.addEventListener('load',prepare);$('#applyBtn').onclick=capture;$('#saveBtn').onclick=async()=>{try{await remote();saveLocal();$('#saveState').textContent='● Draft ذخیره شد';notify('Draft در Firestore ذخیره شد')}catch(e){console.error(e);notify('ذخیره Draft ناموفق بود')}};$('#previewBtn').onclick=()=>{applyAll();notify('Preview به‌روزرسانی شد')};$('#openLive').onclick=()=>window.open('https://mohajer-steel.com/products/steel-billet/','_blank');$('#publishBtn').onclick=()=>$('#publishDialog').showModal();$('#cancelPublish').onclick=()=>$('#publishDialog').close();$('#confirmPublish').onclick=async()=>{try{await remote();await publish();$('#publishDialog').close();notify('انتشار موفق بود؛ سایت اصلی اکنون نسخه Published را می‌خواند')}catch(e){console.error(e);notify('انتشار ناموفق بود')}};$('#clearSelection').onclick=()=>{selected?.classList.remove('mohajer-selected');selected=null;$('#inspector').classList.add('hidden');$('#emptyInspector').classList.remove('hidden')};$('#duplicateBtn').onclick=()=>{if(!selected)return;const c=selected.cloneNode(true);c.dataset.editorNew=Date.now();selected.parentElement.insertBefore(c,selected.nextSibling);notify('کپی در Preview ساخته شد؛ برای ساختار دائمی باید Add/Publish شود')};$('#deleteBtn').onclick=()=>{if(!selected)return;if(!confirm('عنصر از Draft حذف شود؟'))return;undo.push(snapshot());delete drafts[selectedKey];selected.remove();selected=null;$('#inspector').classList.add('hidden');$('#emptyInspector').classList.remove('hidden');saveLocal();historyButtons();notify('عنصر از Draft حذف شد')};$('#undoBtn').onclick=()=>{if(!undo.length)return;redo.push(snapshot());drafts=undo.pop();applyAll();saveLocal();historyButtons();notify('Undo')};$('#redoBtn').onclick=()=>{if(!redo.length)return;undo.push(snapshot());drafts=redo.pop();applyAll();saveLocal();historyButtons();notify('Redo')};$$('.nav').forEach(b=>b.onclick=()=>navView(b.dataset.view));$$('.device').forEach(b=>b.onclick=()=>{$$('.device').forEach(x=>x.classList.remove('active'));b.classList.add('active');device=b.dataset.device;canvas.className='canvas '+device;applyAll()});
$('#textValue').addEventListener('input',e=>{if(selected?.dataset.editorType==='text')text(selected,e.target.value)});$('#linkValue').addEventListener('change',e=>{if(selected){const a=selected.closest('a');if(a)a.href=e.target.value}});$('#newTab').addEventListener('change',e=>{const a=selected?.closest('a');if(a)a.target=e.target.checked?'_blank':''});
})();