(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const adminEmail='amirgzva@gmail.com', draftDoc='draft', publishedDoc='published';
const app=firebase.apps.length?firebase.app():firebase.initializeApp(window.MOHAJER_FIREBASE_CONFIG),auth=app.auth(),db=app.firestore();
const iframe=$('#preview'), canvas=$('#canvas'), toast=$('#toast');
let selected=null, selectedKey=null, selectedType='text', device='desktop', drafts={}, undo=[], redo=[];
const snapshot=()=>JSON.parse(JSON.stringify(drafts));
const notify=m=>{toast.textContent=m;toast.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove('show'),2500)};
const safeText=(el,v)=>{el.replaceChildren();String(v??'').split(/<br\s*\/?>/i).forEach((x,i)=>{if(i)el.append(el.ownerDocument.createElement('br'));el.append(el.ownerDocument.createTextNode(x))})};
const selectorFor=el=>el.dataset.key?`[data-key="${CSS.escape(el.dataset.key)}"]`:el.id?`#${CSS.escape(el.id)}`:(()=>{let a=[],n=el;while(n&&n!==n.ownerDocument.body&&a.length<7){let p=n.tagName.toLowerCase();if(n.classList.length)p+='.'+CSS.escape([...n.classList].find(c=>!c.startsWith('admin-'))||'');let sib=[...n.parentElement.children].filter(x=>x.tagName===n.tagName);if(sib.length>1)p+=`:nth-of-type(${sib.indexOf(n)+1})`;a.unshift(p);n=n.parentElement}return a.join(' > ')})();
function applyDraft(doc,d){if(!d?.selector)return;let el;try{el=doc.querySelector(d.selector)}catch{return}if(!el)return;if(d.type==='image')el.src=d.content||el.src;else safeText(el,d.content);Object.entries(d.styles||{}).forEach(([k,v])=>{if(v!==undefined&&v!=='')el.style[k]=v});if(d.responsive?.[device])Object.entries(d.responsive[device]).forEach(([k,v])=>{if(v)el.style[k]=v})}
function applyAll(){Object.values(drafts).forEach(d=>applyDraft(iframe.contentDocument,d))}
function styleEditor(doc){const s=doc.createElement('style');s.id='mohajer-editor-overlay';s.textContent=`[data-key],img,section,article,button,a,.product-card,.feature-item-new,.dept-card,.ss-product-card{cursor:pointer!important} [data-key]:hover,img:hover,section:hover,article:hover,button:hover,a:hover,.product-card:hover,.feature-item-new:hover,.dept-card:hover,.ss-product-card:hover{outline:2px solid #3478f6!important;outline-offset:2px!important}.mohajer-selected{outline:3px solid #f2b941!important;outline-offset:3px!important}`;doc.head.append(s)}
function prepare(){if(!iframe.contentDocument)return;styleEditor(iframe.contentDocument);applyAll();iframe.contentDocument.addEventListener('click',e=>{const el=e.target.closest('[data-key],img,.product-card,.feature-item-new,.dept-card,.ss-product-card,section,article');if(!el)return;e.preventDefault();e.stopPropagation();select(el)},true)}
function select(el){selected?.classList.remove('mohajer-selected');selected=el;selected.classList.add('mohajer-selected');selectedKey=selectorFor(el);selectedType=el.tagName==='IMG'?'image':el.dataset.key?'text':'container';$('#selectedTitle').textContent=el.dataset.key||el.tagName.toLowerCase();$('#selectedKey').value=selectedKey;$('#emptyInspector').classList.add('hidden');$('#inspector').classList.remove('hidden');$('#rightPanel')?.classList.add('open');const cs=getComputedStyle(el);const map={fontSize:cs.fontSize,fontWeight:cs.fontWeight,lineHeight:cs.lineHeight,letterSpacing:cs.letterSpacing,textAlign:cs.textAlign,textTransform:cs.textTransform,textColor:hex(cs.color),bgColor:hex(cs.backgroundColor),opacity:cs.opacity,margin:cs.margin,padding:cs.padding,gap:cs.gap,width:cs.width,height:cs.height,minWidth:cs.minWidth,maxWidth:cs.maxWidth,position:cs.position,zIndex:cs.zIndex,radius:cs.borderRadius,border:cs.border,shadow:cs.boxShadow};Object.entries(map).forEach(([id,v])=>{const x=$('#'+id);if(x)x.value=v==='rgba(0, 0, 0, 0)'?'#000000':v});$('#textValue').value=selectedType==='image'?'':(el.innerText||el.textContent||'').trim();$('#linkValue').value=el.closest('a')?.href||'';$('#newTab').checked=el.closest('a')?.target==='_blank';$('#bgImage').value=(cs.backgroundImage!=='none'?cs.backgroundImage:'').replace(/^url\(["']?|["']?\)$/g,'');['animation','animationDuration','animationDelay'].forEach(id=>{const x=$('#'+id);if(x)x.value=cs[id]||''});$('#hoverScale').value=drafts[selectedKey]?.hover?.scale||'1';el.scrollIntoView({block:'center',behavior:'smooth'})}
function hex(rgb){const m=rgb?.match(/\d+/g);return m?`#${m.slice(0,3).map(x=>(+x).toString(16).padStart(2,'0')).join('')}`:'#000000'}
function readStyles(){const ids=['fontSize','fontWeight','lineHeight','letterSpacing','textAlign','textTransform','opacity','margin','padding','gap','width','height','minWidth','maxWidth','position','zIndex','radius','border','shadow'];const out={};ids.forEach(id=>{const x=$('#'+id);if(x&&x.value)out[id==='radius'?'borderRadius':id]=x.value});if($('#textColor').value)out.color=$('#textColor').value;if($('#bgColor').value)out.backgroundColor=$('#bgColor').value;if($('#bgImage').value){out.backgroundImage=`url("${$('#bgImage').value}")`;out.backgroundSize='cover';out.backgroundPosition='center'}return out}
function capture(){const key=selectedKey;if(!key)return;undo.push(snapshot());if(undo.length>60)undo.shift();redo=[];const old=drafts[key]||{};drafts[key]={...old,selector:key,type:selectedType,content:selectedType==='image'?(selected.src||''):$('#textValue').value.replace(/\n/g,'<br>'),styles:{...(old.styles||{}),...readStyles()},responsive:{...(old.responsive||{}),[device]:{fontSize:$('#responsiveFont').value||'',width:$('#responsiveWidth').value||'',margin:$('#responsiveMargin').value||'',padding:$('#responsivePadding').value||''}},hover:{scale:$('#hoverScale').value||'1'},schemaVersion:4};applyAll();updateHistory();saveLocal();$('#saveState').textContent='● تغییرات آماده ذخیره';notify('تغییر در Draft اعمال شد')}
function saveLocal(){try{localStorage.setItem('mohajer-editor-pro-draft',JSON.stringify(drafts))}catch{}}
function updateHistory(){$('#undoBtn').disabled=!undo.length;$('#redoBtn').disabled=!redo.length}
async function saveRemote(){if(!auth.currentUser)throw Error('Not authenticated');await db.collection('siteContent').doc(draftDoc).set({content:drafts,updatedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedBy:auth.currentUser.uid});$('#saveState').textContent='● Draft ذخیره شد'}
async function publish(){if(!auth.currentUser)throw Error('Not authenticated');const live=await db.collection('siteContent').doc(publishedDoc).get();const versionId=`v-${Date.now()}`;await db.collection('siteVersions').doc(versionId).set({content:live.exists?live.data().content:{},createdAt:firebase.firestore.FieldValue.serverTimestamp(),createdBy:auth.currentUser.uid,source:'pre-publish'});await db.collection('siteContent').doc(publishedDoc).set({content:drafts,updatedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedBy:auth.currentUser.uid,versionId});notify('نسخه منتشر شد و Snapshot ساخته شد')}
function loadPages(){const box=$('#leftContent');box.innerHTML='';[['صفحه اصلی','/'],['Steel Billet','/products/steel-billet/'],['Steel Beam','/products/steel-beam/'],['Steel Pipe','/products/steel-pipe/'],['Rebar','/products/rebar/'],['Steel Plate','/products/steel-plate/'],['Steel Angle','/products/steel-angle/'],['Steel Channel','/products/steel-channel/'],['Steel Slab','/products/steel-slab/']].forEach(([n,p])=>{const b=document.createElement('button');b.className='page-item';b.innerHTML=`${n}<small>${p}</small>`;b.onclick=()=>{if(p!=='/products/steel-billet/'){notify('در نسخه فعلی Editor فقط Steel Billet فعال است');return}iframe.src='../../products/steel-billet/';$('#pageTitle').textContent=n;$('#pagePath').textContent=p};box.append(b)})}
function loadLocal(){try{drafts=JSON.parse(localStorage.getItem('mohajer-editor-pro-draft')||'{}')}catch{drafts={}}}
async function boot(){loadLocal();loadPages();iframe.addEventListener('load',prepare);try{const s=await db.collection('siteContent').doc(draftDoc).get();if(s.exists&&s.data().content)drafts={...s.data().content,...drafts};applyAll()}catch(e){console.warn(e)}updateHistory()}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button');b.disabled=true;try{await auth.setPersistence(firebase.auth.Auth.Persistence.SESSION);await auth.signInWithEmailAndPassword(adminEmail,$('#adminPassword').value)}catch(err){$('#loginError').textContent='ورود ناموفق بود؛ رمز یا اتصال را بررسی کنید'}finally{b.disabled=false}});
auth.onAuthStateChanged(u=>{if(u&&u.email!==adminEmail)return auth.signOut();const ok=!!u;$('#loginGate').classList.toggle('hidden',ok);$('#app').classList.toggle('locked',!ok);if(ok)boot()});
$('#applyBtn').onclick=capture;$('#saveBtn').onclick=async()=>{try{await saveRemote();saveLocal();notify('Draft ذخیره شد')}catch(e){console.error(e);notify('ذخیره Draft ناموفق بود')}};$('#publishBtn').onclick=()=>$('#publishDialog').showModal();$('#cancelPublish').onclick=()=>$('#publishDialog').close();$('#confirmPublish').onclick=async()=>{try{await saveRemote();await publish();$('#publishDialog').close()}catch(e){console.error(e);notify('انتشار ناموفق بود')}};$('#clearSelection').onclick=()=>{selected?.classList.remove('mohajer-selected');selected=null;$('#inspector').classList.add('hidden');$('#emptyInspector').classList.remove('hidden')};$('#openLive').onclick=()=>window.open('https://mohajer-steel.com/products/steel-billet/','_blank');$('#previewBtn').onclick=()=>{applyAll();notify('Preview از Draft به‌روزرسانی شد')};
$$('.device').forEach(b=>b.onclick=()=>{$$('.device').forEach(x=>x.classList.remove('active'));b.classList.add('active');device=b.dataset.device;canvas.className='canvas '+device;applyAll()});
$('#undoBtn').onclick=()=>{if(!undo.length)return;redo.push(snapshot());drafts=undo.pop();applyAll();updateHistory();saveLocal();notify('Undo')};$('#redoBtn').onclick=()=>{if(!redo.length)return;undo.push(snapshot());drafts=redo.pop();applyAll();updateHistory();saveLocal();notify('Redo')};
$('#duplicateBtn').onclick=()=>{if(!selected)return;notify('Duplicate در این مرحله فقط برای عناصر دارای data-key امن است')};$('#deleteBtn').onclick=()=>{if(!selected)return;if(!confirm('این عنصر از Draft حذف شود؟'))return;undo.push(snapshot());selected.remove();delete drafts[selectedKey];updateHistory();notify('عنصر در Preview Draft حذف شد؛ برای انتشار ذخیره کنید')};
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');const v=b.dataset.view;if(v==='pages')loadPages();else if(v==='elements'){$('#leftContent').innerHTML='<div class="page-item">Heading<br>Text<br>Paragraph<br>Image<br>Button<br>Card<br>Container<br>Divider<br>Video<br>Gallery<br>FAQ</div>'}else if(v==='ai'){$('#leftContent').innerHTML='<div class="page-item"><b>AI Assistant</b><p class="hint">ابتدا یک عنصر را انتخاب کنید؛ AI فقط روی همان هدف مجاز است.</p></div>'}else if(v==='seo'){$('#leftContent').innerHTML='<div class="page-item"><b>SEO Manager</b><p class="hint">Meta Title · Description · Canonical · Robots · Open Graph · Schema</p></div>'}else if(v==='history'){$('#leftContent').innerHTML='<div class="page-item"><b>History</b><p class="hint">تاریخچه Draft و Snapshotهای Publish در Firestore نگهداری می‌شوند.</p></div>'}else{$('#leftContent').innerHTML='<div class="page-item">Settings</div>'}});
})();